### ISSUE TITLE
An option to change font color on retainer list window.

### ISSUE THREAD

**Issue by mithril186** [chalkos/Marketbuddy#18]
### What's your suggestion?

Hello, thanks for making this plugin.

I use the light theme for ffxiv, and its hard to see with the white font.
![image](https://user-images.githubusercontent.com/105821873/169151715-96c33b20-93ec-4e35-b059-9a537ba31179.png)

Is it possible to add an option to change colors?
Thanks again.

**Comment by chalkos** [comment]
Hmm.. are you using a dalamud theme as well and the colors are not being applied correctly? or you like to have a light theme for ffxiv and a dark theme for dalamud?

**Comment by chalkos** [comment]
I could try to change the font there depending on the selected ffxiv theme, instead of using dalamud theme font color... but say if somebody uses a dark blue font color then the price overlay font color will not have the dark blue they have selected

**Comment by chalkos** [comment]
alright, let me know if that fixes the readability of the text in the overlay

**Comment by mithril186** [comment]
It did work, thank you.
![image](https://user-images.githubusercontent.com/105821873/169708764-cc108fac-f71b-43fa-a5ed-6f7cb6881169.png)
