### ISSUE TITLE
Request: configurable undercut value

### ISSUE THREAD

**Issue by unconnecteduk** [chalkos/Marketbuddy#2]
hey, excellent plugin and one I use every hour of every day now. was just wondering if it was possible to add a user-configurable undercut value (via a textbox or something)?

either way, thanks for creating this plugin, its incredibly useful!

**Comment by chalkos** [comment]
Sure, I'll add it

**Comment by Ralphiius** [comment]
Has this feature been added? I'd like to second this request.

**Comment by chalkos** [comment]
done. it's in v0.2.2.4
