### ISSUE TITLE
Plogon just died

### ISSUE THREAD

**Issue by ArkfrostLumas** [chalkos/Marketbuddy#22]
### What's the issue?

Plogon is installed, but in-game it's not running and shows up as not installed.
When I try to install it, it spits out the generic error message that it failed to install.
Also tried deletin it from both installedPlugins and pluginConfig within %appdata% and installing it again, but it still gives me the error message that it couldn't install it.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and Marketbuddy.

**Comment by xPumaa** [comment]
@chalkos has already made a new version with a fix, but he has not made it downloadable yet.
Look here #19 to see if it is the same error

**Comment by chalkos** [comment]
now it's downloadable. needed 1 more click
