### ISSUE TITLE
Feature idea: Auto-refresh current prices window / Disable search rejection

### ISSUE THREAD

**Issue by ArkfrostLumas** [chalkos/Marketbuddy#25]
### What's your suggestion?

Something really cool for marketbuddy would be an option to either auto-refresh the "current prices" window when you open it too fast and it says "Please wait and try your search again.", or to disable this clientside thing that it rejects searches going out too fast to begin with.

I've already talked about this on the official Goat Discord, and to quote the people directly:

goat: 
"maybe something for simple tweaks"
"it's so simple that it's really something SE should do"
"it's a very common thing with this type of design"
caraxi: 
"maybe its in client somewhere"
"yea it should be"
"since its client rejecting search"

But no clue how motivated Caraxi is to look for that for simple tweaks. Just asking around because of that, especially since it's something that sounds like it would fit right into marketbuddy.

Cheers :)

**Comment by chalkos** [comment]
https://ptb.discord.com/channels/581875019861328007/685275026156683280/1003600845545410580

> auto-refresh

I can look into it, sure

> disable this clientside thing that it rejects searches going out too fast to begin with

detectable, can get people banned out of nowhere. not doing this one.

**Comment by ArkfrostLumas** [comment]
Yeah, pretty sure the auto-refresh would be smarter as well. Would already help tremendously not to have to manually open and close that damn window every time over and over again.

**Comment by chalkos** [comment]
I created a new tweak for this
![image](https://user-images.githubusercontent.com/98429/184134485-01c6a229-5214-42bd-8eb7-6a6d90226bf0.png)

Should become available at some point after Cara accepts it

**Comment by chalkos** [comment]
And done. look for it in simple tweaks
