### ISSUE TITLE
Suggestion: Skip clicking adjust

### ISSUE THREAD

**Issue by ArkfrostLumas** [chalkos/Marketbuddy#28]
### What's your suggestion?

Plugin's fantastic already and saves a lot of time, but there's one little option missing that would perfect it:
If that's not going too far, would be cool to have an option to hold a modifier key so when you're right clicking **an already listed item** (not one in your inventory) it adjusts the price to the value in your clipboard.

Would be cool if when you're selling the same item 20x you can just adjust the price of the first one, then hold a modifier and right click every item once in the list of items that are already on sale, to adjust the prices instead of having to right click, then aim at "Adjust price" and click again.

**Comment by xPumaa** [comment]
Uhm. You mean the function that already exists?

**Comment by xPumaa** [comment]
![image](https://user-images.githubusercontent.com/35280763/204772851-fa336032-ef15-4fd8-9ce9-b252f1759d97.png)

**Comment by chalkos** [comment]
@ArkfrostLumas you mean #26 ?

**Comment by ArkfrostLumas** [comment]
@chalkos yes I mean exactly that :)

**Comment by chalkos** [comment]
alright, closing this one as it is a duplicate
