### ISSUE TITLE
Request: Gil Net Worth Tracking

### ISSUE THREAD

**Issue by kinderoth** [chalkos/Marketbuddy#3]
I was wondering if it would be possible to add something that showed your spent/gained gil for a time period or your net gil across all your retainers.

 I know teamcraft does something similar but it bugs out if you change characters for some reason and I was looking to for easier way to track profit/loss.

Other thought was showing what you've spent or gained on a given item?

**Comment by chalkos** [comment]
I've thought about it but in the end it seemed like too much work for something that teamcraft already does.

If I develop the plugin to include tracking per item I'd have to start thinking about it as a marketboard tools suite (like tradeskillmaster is for wow) and for now I'd like to keep it simple (I don't have the time to develop and support a suite like that).
