### ISSUE TITLE
Update for latest dalamud

### ISSUE THREAD

**Issue by anon88391** [chalkos/Marketbuddy#32]
With the 6.3 patch dalamud has introduced some changes and the plugin requires an update to work.

**Comment by xPumaa** [comment]
Just wait

**Comment by chalkos** [comment]
> With the 6.3 patch dalamud has introduced some changes and the plugin requires an update to work.

"Wow thanks for letting me know!" - was that the answer you expected?

Dalamud isn't even publicly released for 6.3 so why are you comming in here being way too annoying way too early?

Go write "when plogon" somewhere else
