### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by cat-xiv** [chalkos/Marketbuddy#45]
### What are you trying to do?

When using ctrl to quickly price items, game crashes on 2nd item that im listing.

### What is the expected behavior?

pricing 2nd item should get priced with whatever is in clipboard

### What actually happened?

game just hard crashes without stacktrace or writing anything to the logfile.

resetting config doesnt help.

No clue what changed afaik there was no update. and it still worked a few weeks ago.

tried resetting the settings. and cleanboot without any other plugin running

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and Marketbuddy.

**Comment by chalkos** [comment]
Seems like you need to switch off the staging (`/xlbranch` - release - pick - restart)

let me know if it works

**Comment by cat-xiv** [comment]
yep that fixed it
