### ISSUE TITLE
[Marketbuddy] Clipboard does not contain a valid price

### ISSUE THREAD

**Issue by yuyu-yuyuko** [chalkos/Marketbuddy#47]
### What are you trying to do?

trying to copy the price with 1gil undercut to the clipboard

### What is the expected behavior?

the 1gil undercut price gets copied to the clipboard

### What actually happened?

error message "[Marketbuddy] Clipboard does not contain a valid price"

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and Marketbuddy.

**Comment by chalkos** [comment]
that message happens when quick-posting an item. try following the bullet points here https://github.com/chalkos/Marketbuddy#features

**Comment by yuyu-yuyuko** [comment]
it's not copying the price in the first place, no matter what i try the plugin wont copy the price with 1gil undercut to the clipboard
