### ISSUE TITLE
Toggle for behavior with opening current price list

### ISSUE THREAD

**Issue by DenL** [chalkos/Marketbuddy#5]
Hello thanks for this great plugin!

The current behavior allows for opening current price list when adjusting price, or to hold shift to prevent that from happening. Could there be another toggle to reverse that behavior? Hold shift to open current price list; behaves normally if shift is not held.

**Comment by chalkos** [comment]
Soounds good to me, I'll add it in

**Comment by chalkos** [comment]
Actually going to bind this to ALT, because SHIFT could conflict with another option.
I'll make it so ALT will open/prevent opening the history when the price list opens.

**Comment by chalkos** [comment]
![image](https://user-images.githubusercontent.com/98429/164212473-bf3c7035-3865-40bb-b5d5-049637d58da3.png)

![image](https://user-images.githubusercontent.com/98429/164212526-f603853d-fae8-44dd-9339-eb14bbc2a488.png)

**Comment by DenL** [comment]
Sorry I might not have been clear before. I was looking to have it so that holding down shift (alt in this case) would open the current price list (not price history), not holding down would just open the adjust price window. Basically a toggle to reverse the behavior with shift.

**Comment by chalkos** [comment]
![image](https://user-images.githubusercontent.com/98429/164274602-24337e42-456c-44ed-a46b-250eecd0ee70.png)

![image](https://user-images.githubusercontent.com/98429/164274736-3280848d-5dff-47ea-aaea-0d5688c872b1.png)

like this?

**Comment by DenL** [comment]
Yes thank you!

**Comment by chalkos** [comment]
Nice, I'll have the code done in a bit and release another version

**Comment by chalkos** [comment]
Done. it's in v0.2.2.5
