### ISSUE TITLE
Latest update crashing when holding Ctrl to bulk update prices

### ISSUE THREAD

**Issue by Felys1998** [chalkos/Marketbuddy#7]
Crashdump message:
`Unhandled exception at 0x00007FFD89EA43C3 in ffxiv_dx11.exe.15144.dmp: 0xC0000005: Access violation reading location 0x0000000000000108.`

**Comment by Felys1998** [comment]
repro steps on my end:
1. Open an item e.g. a potion and click to update its price and penny the other guy
2. press ctrl and click on the next item in my retainer's sale list
3. game crashes to desktop with access violation

**Comment by Felys1998** [comment]
happens across 2 installs with varying addon lists. wasn't happening prior to today.

**Comment by chalkos** [comment]
Confirmed. fixing it

**Comment by chalkos** [comment]
Fixed version should be available now (or in a few minutes anyway because of github caching)
